# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-backend
        image: gcr.io/arc-design-challenge/fastapi-backend:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@postgres:5432/mydb"  # Update if using Cloud SQL
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP


#TODO 
#1. Look into postgres deployment, fix crashloopbackoff
#2. Check that backend deployment now works
#3. Access react site from the internet