# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Init container to create the necessary subdirectory and set permissions
      initContainers:
      - name: init-postgres
        image: busybox
        command:
        - sh
        - -c
        - |
          mkdir -p /var/lib/postgresql/data/pgdata
          chown -R 999:999 /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql/data

      # Main PostgreSQL container
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata  # Set the PGDATA environment variable
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
