version: '3.8'

services:
  frontend:
    build:
      context: ./my-react-app
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend
  backend:
    build:
      context: ./myfastAPI
    container_name: fastapi-backend
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydb
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
volumes:
  postgres-data:
networks:
  mynetwork:
    driver: bridge
